### ISSUE TITLE
Todo-list Issues

### ISSUE THREAD

**Issue by joel-kalema** [EzekielUtshudi/To-Do-List#9]
- [ ] Your job looks professional 👍 
- [ ] Everything looks good, but we found an issue when we add more items, your lear button disappears. Try to fix it, please.

**Comment by joel-kalema** [comment]
- [ ] Job will done ㊗️

**Comment by EzekielUtshudi** [comment]
Thank you guys for the positive feedback and I am correcting that right now.
